s='hello world'
print(s.capitalize())
print(s.count('h'))
print(s.find('d'))
print(s.center(20,'z'))
print(s.isalpha())
print(s.islower())
print('hello'.islower())
print('hello'.endswith('o'))
print('hello'.split('e'))
print('hello'.partition('l'))